language: ruby
rvm:
  - 2.6.3
os: linux
dist: focals

branches:
  only:
  - master

services:
  - docker

install:
  - sudo snap install kubectl --classic
  - sudo snap install doctl
  - sudo snap install yq

before_script:
  - mkdir ${HOME}/.kube
  - echo "$KUBECONFIG" | base64 --decode > ${HOME}/.kube/config
  - doctl auth init -t "$DOCTL"
  - doctl registry login

script:
  - bundle install
  - bundle exec jekyll build

after_scriptß:
  - tag=registry.digitalocean.com/tomas-registry/tomasroy.com:$TRAVIS_BUILD_NUMBER
  - docker build -t $tag .
  - docker push $tag
  - ./deploy.sh $tag

deploy:
- provider: script
  skip_cleanup: true
  script: deploy.sh $tag
  on:
    branch: master
