language: ruby
rvm:
  - 2.6.3
os: linux
dist: focals

branches:
  only:
  - master

services:
  - docker

install:
  - sudo snap install kubectl --classic
  - sudo snap install doctl
  - sudo snap install yq

before_script:
  - mkdir ${HOME}/.kube
  - echo "$KUBECONFIG_ENC" | base64 --decode > ${HOME}/.kube/config
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - bundle install
  - bundle exec jekyll build

before_deploy:
  - tag=minicreative/tomasroy.com:$TRAVIS_BUILD_NUMBER
  - docker build -t $tag .
  - docker push $tag

deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh $tag
  on:
    branch: master
