language: ruby

branches:
  only:
  - master

services:
  - docker

install:
  - snap install kubectl --classic
  - snap install doctl
  - snap install yq

before_script:
  - mkdir ${HOME}/.kube
  - echo "$KUBECONFIG" | base64 --decode > ${HOME}/.kube/config
  - doctl auth -t "$DOCTL"
  - doctl registry login

script:
  - tag=registry.digitalocean.com/tomas-registry/tomasroy.com:$TRAVIS_BUILD_NUMBER
  - docker build -t $tag .
  - docker push $tag
  - ./deploy.sh $tag

deploy:
- provider: script
  skip_cleanup: true
  script: deploy.sh $tag
  on:
    branch: master
