language: node_js

branches:
  only:
  - master

script:
- echo "No build or scripts, just deployments"

before_deploy:
- ssh-keyscan -H $deploy_host >> $HOME/.ssh/known_hosts
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: ./deploy.sh tomasroy.com
  on:
    branch: master
