apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomasroy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomasroy
  template:
    metadata:
      labels:
        app: tomasroy
    spec:
      containers:
      - name: main
        image: $IMAGE
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tomasroy
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tomasroy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tomasroy-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - tomasroy.com
    secretName: tls-cert
  rules:
  - host: tomasroy.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tomasroy
            port:
              number: 80